export const ROUTE_NAME = {
  BASE: "/",
  SIGNUP: "/signup",
  DASHBOARD: "",
};

export const ROUTE_DEFINATION = {
  BASE: ROUTE_NAME.BASE,
  SIGNUP: ROUTE_NAME.SIGNUP,
  DASHBOARD: ROUTE_NAME.DASHBOARD,
};
